export type StoreFactoryV2ErrorCode =
  | "BUILD_IDEMPOTENCY_CONFLICT"
  | "BUILD_ALREADY_TERMINAL"
  | "BUILD_PHASE_TRANSITION_INVALID"
  | "BUILD_STATE_TRANSITION_INVALID"
  | "REVISION_ASSEMBLER_REQUIRED"
  | "BASE_REVISION_INVALID"
  | "REVISION_CANDIDATE_INVALID"
  | "REVISION_QA_FAILED"
  | "REVISION_NOT_FOUND"
  | "REVISION_STORE_MISMATCH"
  | "REVISION_STATUS_CONFLICT"
  | "REVISION_TRANSITION_INVALID"
  | "PREVIEW_POINTER_CONFLICT"
  | "PREVIEW_REVISION_NOT_APPROVED"
  | "PREVIEW_TARGET_ALREADY_ACTIVE"
  | "PREVIEW_PROMOTION_TARGET_INVALID"
  | "PREVIEW_ROLLBACK_TARGET_INVALID"
  | "STORE_NOT_PREVIEW_ACTIVE"
  | "REPOSITORY_INVARIANT_VIOLATION";

export class StoreFactoryV2Error extends Error {
  readonly code: StoreFactoryV2ErrorCode;

  constructor(code: StoreFactoryV2ErrorCode, message: string) {
    super(message);
    this.name = "StoreFactoryV2Error";
    this.code = code;
  }
}
